package com.situ.ssm.mapper;

import com.situ.ssm.pojo.ClassCourseExample;
import com.situ.ssm.pojo.ClassCourseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int countByExample(ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int deleteByExample(ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int deleteByPrimaryKey(ClassCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int insert(ClassCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int insertSelective(ClassCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    List<ClassCourseKey> selectByExample(ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") ClassCourseKey record, @Param("example") ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    int updateByExample(@Param("record") ClassCourseKey record, @Param("example") ClassCourseExample example);
}