package com.situ.ssm.pojo;

public class ClassCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.class_id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.course_id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.class_id
     *
     * @return the value of class_course.class_id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.class_id
     *
     * @param classId the value for class_course.class_id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.course_id
     *
     * @return the value of class_course.course_id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.course_id
     *
     * @param courseId the value for class_course.course_id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}