package com.situ.ssm.pojo;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbggenerated Tue Jul 25 10:27:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}